name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 11 12 * *'

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - name: Try updating the version
        run: |
          npm install
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm run publish
          git push --follow-tags
